vim-test/vim-test

autoload/test/go/gotest.vim

- Fix go test -run. If we run a file, only use the file name. If we run
a targeted test, don't include the file name.

Update gotest.vim, fix -run flag, run from any file

---

autoload/test/go/gotest.vim

- 'file' option will test all the *_test.go files in the current directory by running 'go test'.
Go doesn't have a concept of running all tests in a single file without some tricky file inclusion.
- 'suite' option will run all the tests in the current directory and all subdirectories by running 'go test ./...'.

"Fix" go testing options since go doesn't test single files

---

autoload/test/python.vim
spec/fixtures/nose/test_class.py

The fix for issue #29 will still fail when the class name contains
underscores or numbers, both of which are valid in python.  I noticed
that the regex also allows dots, which are not valid in a python class
name ( http://stackoverflow.com/a/10120327 )

allow underscores and numbers in python class names

---

autoload/test/python/nose.vim

by default, nose looks for a file with "test" at the beginning of the
name, or anywhere in the filename after a word boundary like underscore
or dot.
http://nose.readthedocs.org/en/latest/api/config.html

allow "test" to be anywhere in a filename

---

README.md
autoload/test/php.vim
autoload/test/php/phpunit.vim
doc/test.txt
plugin/test.vim
spec/fixtures/phpunit/NormalTest.php
spec/phpunit_spec.vim

I am trying to create a pull request to add PHPUnit support but at the moment I am having trouble getting my tests to pass as `Expect exists('g:test#last_command') == 1` is failing. Is there something else I need to do to hook it in?

PHPUnit support

---

autoload/test/php/phpunit.vim

This updates the phpunit runner to look for phpunit in standard Composer ./vendor/bin and ./bin directories

Look for phpunit in standard Composer ./vendor/bin and ./bin directories

---

README.md

I had to go through the source to find the name of the runner to use with Django, originally I used `'django'` but that didn't work, and the docs where not clear.

Added djangotest

---

autoload/test/javascript.vim
spec/fixtures/mocha/test/context.js
spec/mocha_spec.vim

Mocha's BDD test runner adds a `context` global, much like rspec's `context`:
https://mochajs.org/#bdd. Previously the namespace regex would miss this, which
would cause the grep to be incomplete. Updates the mocha regex to match the
word `context` in the same place as the word `describe`.
Adds tests that this new regex behaves as expected.

javascript: alias "context" to "describe"

---

autoload/test/php/phpunit.vim
spec/fixtures/phpunit/NormalTest.php
spec/phpunit_spec.vim

Added nearest support to PHPUnit using --filter argument

Added nearest support to PHPUnit using --filter argument

---

autoload/test/php/phpunit.vim
spec/phpunit_spec.vim

Fixed the order so that PHPUnit --filter option is before test file argument

Fixed the order so that PHPUnit --filter option is before test file argument

---

autoload/test/python/djangotest.vim
spec/djangotest_spec.vim

This allows manage.py to have no 'x' flag

DjangoTest: launch manage.py with python

---

autoload/test/php/phpunit.vim
spec/fixtures/phpunit/NormalTest.php
spec/phpunit_spec.vim

The simplest solution was implemented, due to my lack of VimL knowledge. Now it works, but not because of the `@test` annotation, but because it is the nearest method.
The way it is it will consider any method as a test method. That may be considered a bug.
Of course it can be improved, but IMO it is better to see PHPUnit's message "no tests executed!" when cursor is near a non-test method than not being able to run a single method when it is an annotated method.

Can run nearest phpunit test marked with @test annotation

---

autoload/test/strategy.vim

Provide a variable that can be used to prevent the screen from being
cleared before each test run.  Set `g:test#preserve_screen` to non-zero
to disable the clear screen functionality.
By default, the existing clear screen behavior is kept.

Don't clear the screen before running tests

---

autoload/test/php/phpspec.vim

Use --no-ansi with PHPSpec if strategy doesn't support colors

---

autoload/test/javascript.vim
autoload/test/javascript/intern.vim
plugin/test.vim
spec/fixtures/intern/outside.js
spec/fixtures/intern/tests/bdd.js
spec/fixtures/intern/tests/functional/bdd.js
spec/fixtures/intern/tests/functional/object.js
spec/fixtures/intern/tests/functional/tdd.js
spec/fixtures/intern/tests/intern.js
spec/fixtures/intern/tests/object.js
spec/fixtures/intern/tests/tdd.js
spec/fixtures/intern/tests/unit/bdd.js
spec/fixtures/intern/tests/unit/object.js
spec/fixtures/intern/tests/unit/tdd.js
spec/intern_spec.vim

This pull request adds Intern support (#105) with the following features:
- Supports BDD/TDD/Object interfaces.
- Supports both unit and functional tests.
- Supports `TestNearest`, `TestFile`, and `TestSuite`.
- Allows specifying Intern's test runner (`intern-client` vs `intern-runner`) through `g:test#javascript#intern#test_runner`.
- Allows specifying Intern's configuration module (`tests/intern`) through `g:test#javascript#intern#config_module`.
Things to note:
- It is impossible to implicitly detect which test runner to use. Therefore, the default is `intern-client`. However, the user can change it through `g:test#javascript#intern#test_runner` to `intern-runner`.
- It is impossible to implicitly detect whether the test is a unit test or a functional test without assumptions. Intern …

Add support for JavaScript's Intern framework (#2)

---

autoload/test/go/gotest.vim
spec/gotest_spec.vim

In Go, additional packages can live in subdirectories. In order to run
them properly, the subdirectory needs to be specified.
This fix ensures that the nearest test (by name) is run in the
appropriate directory.

Run Go nearest tests from their directories

---

autoload/test/javascript/mocha.vim
spec/mocha_spec.vim

Improve Mocha's TestNearest regex polyfill (#110). If the nearest test detected is:
- Namespace(s) only, then `^` will be prefixed only. This allows running anything starting with the namespace(s) pattern only (all sub-namespaces and sub-tests).
- Test inside namespace(s), then `^` will be prefixed, and `$` will be postfixed. This allows running anything exactly matching the test pattern inside the namespace(s).
- Test not inside any namespace, then `$` will be postfixed only. This allows running test(s) ending with the test pattern.
- Nothing, then an empty string will be returned.
I've updated `mocha_spec.vim` to reflect the new changes. I've also tested the new changes with both vim-flavor and mocha installation quickly.

Improve Mocha's TestNearest regex polyfill

---

autoload/test/javascript.vim
autoload/test/javascript/intern.vim
spec/fixtures/intern/tests/qunit.js
spec/intern_spec.vim

**Improvements:**
- Add support for Intern's QUnit interface.
- Move Intern's namespace and test pattern away from `javascript.vim` to `intern.vim`. Some of the patterns are specific to Intern, and should not be globalized for other javascript test frameworks. Since Intern can support other testing interfaces, the default javascript patterns were added as well.
- Improve `TestNearest` regex polyfill (#110). If the nearest test detected is:
- Namespace(s) only, then `^` will be prefixed only. This allows running anything starting with the namespace(s) pattern only (all sub-namespaces and sub-tests).
- Test inside namespace(s), then `^` will be prefixed, and `$` will be postfixed. This allows running anything exactly matching the test pattern inside the namespace(s).
- Test without any …

Add support for Intern's QUnit interface and improve nearest test regex

---

autoload/test/strategy.vim

Currently, the external terminal need to be CDed into Vim's CWD manually for the test runner to execute successfully. This tiny PR automatically CD into Vim's CWD before executing any test runner in external terminals. Test with Terminal.app successfully, and should work with other terminals.

CD into CWD before executing a runner in external terminals

---

README.md

The previous link no longer exists and this seems to be the currently maintained fork.

Update tslime link in README

---

README.md
autoload/test/javascript/tap.vim
plugin/test.vim
spec/fixtures/tap/test/normal.js
spec/fixtures/tap/tests/normal.js
spec/tap_spec.vim

Add support for JavaScript TAP-based testing frameworks, as requested in #97.
- It can detect a locally installed `tape` or `tap` (under the local `node_modules/.bin/*` only).
- It can be extended to support any other TAP-based frameworks using the config `g:test#javascript#tap#runners`.
- It can be configured to use any locally installed reporters through the config `g:test#javascript#tap#reporters`
- If multiple reporters are specified and only one of them is installed, it will be used as the reporter.
- If multiple reporters are specified and installed locally, they will be piped one after the other. Of course, all reporters except the last one must provide TAP output for the following reporter. Only certian reporters produce TAP output (e.g. `tap-notify`).
- If multiple reporters are …

Add support for JavaScript TAP-based testing frameworks

---

autoload/test/javascript/karma.vim
plugin/test.vim
spec/karma_spec.vim

Add a basic karma runner which doesn't restrict the tests being run in any way due to the limitations in how `karma` selects the tests to run.
resolves #123

Add basic karma runner

---

autoload/test/ruby/m.vim

https://github.com/qrush/m
The default minitest runner sometimes has issues with the nested spec
syntax. Describe > describe etc.
Let's not reinvent the wheel, let's use M.
Example .vimrc settings:
" register the M runner.
let test#runners = {'Ruby': ['M']}
" you want to set the runner_commands because otherwise the default
" minitest runner will be used. In our case we had multiple test
" suites.. legacy!
let g:test#runner_commands = ['M', 'Cucumber', 'Rspec']

Add runner for M, a Test::Unit runner that runs tests by line number

---

README.md
autoload/test/javascript/karma.vim
plugin/test.vim
spec/fixtures/karma/normal_spec.js
spec/karma_spec.vim

Improve the way we detect karma as our test runner so that it is more
relaxed on the file names, but will check for the karma executable and
the presence of the karma.conf.js file. The name and/or location of the
karma.conf.js can be customized by setting
g:test#javascript#karma#conffile.
Closes #127

Improve karma detection and add customizable karma.conf.js

---

autoload/test/python.vim

In python 3.5 syntax for creating coroutines on a language level have been added.
Because of that libraries like pytest-asyncio have been created, that can decorate test that is written as a coroutine object and run it in a loop.
```
@pytest.mark.asyncio
async def test_some():
assert await some_awaitable() == some_expected_result

async tests support for python

---

autoload/test/strategy.vim
doc/test.txt

To catch the results of the test to a buffer, use `:Verbose TestFile` with Tim Pope's Scriptease plugin.

Add VimProc as a new strategy

---

autoload/test/strategy.vim

When I like to run a test, the `cmd.exe` says:
The system cannot find the path specified
The source of this problem is that Windows using `&` to separate
commands, `;` for command line parameters.
See:
www.microsoft.com/resources/documentation/windows/xp/all/proddocs/en-us/ntcmds_shelloverview.mspx

Fix 'basic' startegy on Windows

---

autoload/test/python/pytest.vim

(pytest test_some.py::test_nearest vs pytest test_some.py -k test_nearest)

test_nearest is executing exactly one test

---

autoload/test/python/pytest.vim

Thanks to github it's all in the name. I've found some time to properly implement this. I've tested two use cases. One when test is a module level function and one where test is a method of a class.
Wasn't very hard to do, because you've already searching for namespace and it's available. The only thing that stopped me before is that my knowledge of vimscript was worse than it is now.

nearest strategy now executes only one test and test classes work also

---

autoload/test/ruby/rails.vim

I am not exactly sure why though, at least for my environment, Rails version detection always fails because `cat Gemfile.lock` returns long one-liner which includes newline symbols and the regex also fails because of leading whitespaces in `Gemfile.lock`.
So I have changed the Rails version detection method to more reliable one using Vim builtin function.
How does this sound to you?
FYI: 
macOS 10.12.1
```
$ vim --version                                                                                                                                                    
VIM - Vi IMproved 8.0 (2016 Sep 12, compiled Dec 16 2016 10:35:52)
MacOS X (unix) version
Included patches: 1-134
Compiled by Homebrew
```

Change rails version detection method

---

autoload/test/javascript/karma.vim

I am currently working on application using [nwb which requires you to run nwb test](https://github.com/insin/nwb/blob/master/docs/Commands.md#test). This is a quick PR to get vim-test to check for the presence of the nwb config.

If there is a nwb config present then run `nwb test`

---

autoload/test/crystal.vim
autoload/test/crystal/crystalspec.vim
plugin/test.vim
spec/crystal_spec.vim
spec/fixtures/crystal/normal_spec.cr

This adds support for the crystal programming language, which has a built in test runner that is much like rspec.

Add support for crystal

---

README.md
autoload/test/javascript/jest.vim
plugin/test.vim
spec/fixtures/jest/__tests__/context-test.js
spec/fixtures/jest/__tests__/normal-test.coffee
spec/fixtures/jest/__tests__/normal-test.js
spec/fixtures/jest/__tests__/normal-test.jsx
spec/fixtures/jest/outside-test.js
spec/jest_spec.vim

Runs tests from the `__tests__` directory, file names must end in `-test.js|jsx|coffee` .
I can make the file pattern more flexible, that's open to discussion.

Add support for Jest

---

README.md
autoload/test/cs.vim
autoload/test/cs/dotnettest.vim
plugin/test.vim
spec/dotnet_spec.vim
spec/fixtures/dotnet/Tests.cs

This pull request adds a runner for the dotnet cli command `dotnet test`. 
I'd appreciate any input about the logic I am using to find the nearest `.csproj` file, I'm not great with vimscript. Finding the nearest `.csproj` file is required because the path is a required argument to `dotnet test`. I've tested this out using an underlying xunit test project as well as an mstest one, both work fine. All of the functionality `:TestFile`, `:TestSuite`, and `:TestNearest` work as expected.

Add dotnet test runner

---

README.md
autoload/test/strategy.vim
doc/test.txt

This is a neomake strategy, as per the discussion in https://github.com/janko-m/vim-test/issues/153.
I'm not sure if the implementation is perfect but it works with Dispatch where possible but otherwise falls back to the using the last set `errorformat`. 
I tried to use a convention similar to https://github.com/markwoodhall/vim-cljreloaded/blob/master/plugin/cljreloaded.vim#L15 in order to check if the `compiler_for_program` function exists but I believe that will only return true if the function has actually been loaded, which might not be the case if it has not been run yet.

Add neomake strategy

---

README.md
autoload/test/python/pyunit.vim
doc/test.txt
plugin/test.vim
spec/pyunit_spec.vim

Support for python's built-in unittest as a last resort if none of pytest, nose or django are installed.

Support for python's built-in unittest

---

README.md
autoload/test/go.vim
autoload/test/go/ginkgo.vim
autoload/test/go/gotest.vim
doc/test.txt
plugin/test.vim
spec/fixtures/ginkgo/mypackage/normal_test.go
spec/fixtures/ginkgo/normal_test.go
spec/ginkgo_spec.vim
spec/go_runner_spec.vim

[Ginkgo](https://github.com/onsi/ginkgo) is a BDD-style Golang testing framework.
Although Ginkgo tests can be run by `go test`, `gotest.vim` is unable to build positions because of its BDD style. `ginkgo.vim` builds positions based on BDD keywords offered by Ginkgo: `It`, `Describe` and `Context`.
For your reference, Ginkgo cli offers two ways to run a subset of tests:
* regex on spec: `ginkgo --focus="should return 0"`
* regex on test file path: `ginkgo --regexScansFilePath=true --focus=package/some_test.go`
I'm fairly new to vim-script. Any suggestion will be appreciated, Thanks!

add support for the Ginkgo framework of Go

---

autoload/test/java/maventest.vim
spec/maventest_spec.vim

maventest.vim could not support the vim-test way of adding options for a test
runner. For example if a user tried to pass `-f /path/to/pom.xml` as an option
parameter as follows:
`let test#java#maventest#options = '-f /path/to/pom.xml'`
the script would end up calling
`mvn test -Dtest=-f /path/to/pom.xml TestFileName`
which cannot work. Corrected the argument handling to support any number of
option parameters. The assumption is that 0 to 1 test names are passed to the
plugin. The example above now results to:
`mvn test -f /path/to/pom.xml -Dtest=TestFileName`
Fixes #194

FIX better support for options in maventest

---

README.md
autoload/test/javascript.vim
autoload/test/javascript/intern.vim
autoload/test/javascript/jasmine.vim
autoload/test/javascript/jest.vim
autoload/test/javascript/karma.vim
autoload/test/javascript/mocha.vim
autoload/test/javascript/tap.vim
spec/fixtures/intern/package.json
spec/fixtures/jasmine/package.json
spec/fixtures/jest/package.json
spec/fixtures/karma/package.json
spec/fixtures/lab/package.json
spec/fixtures/mocha/package.json
spec/fixtures/tap/package.json
spec/jest_spec.vim

This arises for #187 as based on this plugin's motto of zero configuration we should try to infer the runner from the package.json

Detect the JavaScript runner based on the package.json

---

README.md

Go code example for specific runner was missing
3 ticks which bugged the whole ruby paragraph.
Fixed by adding back the 3 ticks to the vim example.

Fix readme formatting.

---

autoload/test/python/pytest.vim

As stated [here](https://pytest.readthedocs.io/en/reorganize-docs/new-docs/user/naming_conventions.html).
Taken as reference [the nose modification](https://github.com/janko-m/vim-test/pull/32/files)

Let test be in front or at the end.

---

README.md
autoload/test/swift.vim
autoload/test/swift/swiftpm.vim
doc/test.txt
plugin/test.vim
spec/fixtures/swiftpm/Package.swift
spec/fixtures/swiftpm/Sources/VimTest.swift
spec/fixtures/swiftpm/Tests/LinuxMain.swift
spec/fixtures/swiftpm/Tests/VimTestTests/VimTestTests.swift
spec/swiftpm_spec.vim

Swift Package Manager ships a test runner that is accessible via `swift test`.
This commit adds support for working with `swift test` via vim-test.
There's definitely some fragility in here still that might need to get worked
out over time. Off the top of my head, some potential issues:
- Users might locate their tests in a directory named something other than
"Tests". Doing so would break the test file detection (and the module name
parsing).
- If users use a test lib like Quick, this won't properly parse module info
(and filtering Quick tests with swift test doesn't work at all).
That being said, I think this is a good start, and getting this into the
plugin would mean being able to deploy fixes for these issues by tweaking the
regexes instead of needing to write this whole thing from …

Add support for swift test

---

README.md
autoload/test/elm/elmtest.vim
doc/test.txt
plugin/test.vim
spec/elmtest_spec.vim
spec/fixtures/elmtest/tests/NormalTest.elm

This PR adds initial basic support for [Elm](http://elm-lang.org/) and [elm-test](https://github.com/elm-community/elm-test) to vim-test. Thanks :slightly_smiling_face:

Add initial support for Elm and elm-test

---

README.md
autoload/test/ruby/cucumber.vim
autoload/test/ruby/m.vim
autoload/test/ruby/minitest.vim
autoload/test/ruby/rails.vim
autoload/test/ruby/rspec.vim

This pull request adds an option `test#ruby#use_binstubs` (defaults to 1/true) to allow users to configure vim-test to ignore any binstubs that may exist.
Sometimes you're working on a project and have no control over whether there are binstubs in the directory, but you don't want to (or can't) use them. This adds an option so they get ignored.

Option to turn Ruby binstubs off if they exist

---

autoload/test/java/maventest.vim
spec/fixtures/maven/MathTestCase.java
spec/fixtures/maven/MathTests.java
spec/fixtures/maven/TestMath.java
spec/maventest_spec.vim

maventest should match all Maven Surefire test filename patterns.
```
Test*.java
*Test.java
*Tests.java
*TestCase.java
```
http://maven.apache.org/surefire/maven-surefire-plugin/examples/inclusion-exclusion.html
Fixes https://github.com/janko-m/vim-test/issues/206.

Make maventest match all surefire filename patterns (janko-m/vim-test#206)

---

autoload/test/javascript/mocha.vim
spec/mocha_spec.vim

Pulled out separately from the MochaWebpack branch I'm working on. I believe this better handles getting mocha to find all the files in a suite
recurses into sub dirs
tries both test and tests

Improve mocha suite test running

---

autoload/test/php/phpspec.vim

Arises from #215. I am able to get it to work when searching for "PhpSpec" but not "PhpSpec\ObjectBehavior" for reason.

Change PhpSpec test file detection to use readfile

---

README.md
autoload/test/php/dusk.vim
doc/test.txt
plugin/test.vim
spec/dusk_spec.vim
spec/fixtures/dusk/BrowserTest.php

Add Laravel Dusk tests to vim-test.
Implementation should be almost exactly similar to PhpUnit; tests should only run differently if `use Laravel\Dusk\Browser` exists in the file.
To avoid worrying about folder structure (that seemed a bit brittle to me), I just tested for the presence of 'use Laravel\Dusk\Browser' and put the Dusk test runner before PHPUnit's to ensure it ran first (since it's using the same file matching pattern).

Added Laravel Dusk runner

---

README.md
autoload/test/strategy.vim

I see that we have [Dispatch](https://github.com/janko-m/vim-test/blob/master/autoload/test/strategy.vim#L35) strategy, but I would like to run test in background, so I added this dispatch_background strategy

Add Dispatch! background variation

---

autoload/test/php/phpunit.vim
spec/phpunit_spec.vim

Sometimes, a test method is a bit too generic and you end running multiple tests instead of **just** the nearest test. Take the following methods for example: `testFoo`, `testFooBar`, `testFooBaz`. If you test nearest inside `testFoo` then you end up running all 3 of those methods. Since phpunit supports regex, this syntax prevents that from happening. I specifically ran into this when testing a fluent query builder that had a lot of `where` methods, such as `where`, `whereNull`, `whereNotNull`, etc.
I'd be more than willing to run a test to ensure that phpunit only runs 1 test (say by capturing the output of phpunit) I'd be down to write it, but I'm not familiar with vspec at all so I would need some direction!

Add regex to force only a single test to run

---

autoload/test/python.vim
spec/fixtures/nose/test_method.py
spec/pytest_spec.vim

This addresses the bug reported in #232

Check Python test class namespace is prefixed with Test

---

autoload/test/javascript/tap.vim

I work on a project that has a sub-dependency that has `tape` as a normal dependency vs a development dependency; thus making the original checker for `tape` think that it should use it over the top-most testing tool (that being mocha).
In other words, this avoids the blunt checking for testing tools and checks the the top-most project's approach.
This aims to use the same kind of detection that mocha does to counteract mis-defined projects like this.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/janko-m/vim-test/255)

Do Proper Checking for Tape

---

autoload/test/strategy.vim

**Why we need this change?**
I'm having an issue with my setup where I'm using vtr dispatch strategy and I'm targeting
a tmux pane that runs a docker container. My project path in the docker container is different from the one in my host machine. So whenever I'm executing a test, there is cd getcwd() that will
be called and it resulted with no such file or directory.
**What has changed?**
I've removed the related code for changing to test directory in strategy file.

[Option 3] Remove Change Directory in Strategy

---

autoload/test/php/phpunit.vim
spec/phpunit_spec.vim

Without this change no test was executed by phpunit 6.3.0.
See https://phpunit.de/manual/6.5/en/textui.html#textui.examples.filter-patterns

Fixed phpunit filter

---

autoload/test/php/phpspec.vim
spec/phpspec_spec.vim

PHPSpec allows to specify a line number to run only the specification defined on that line. See http://www.phpspec.net/en/stable/cookbook/console.html#run-command. So, it's better than nothing :).

Support running the nearest test for the PhpSpec

---

spec/nose_spec.vim
spec/strategy_spec.vim
spec/support/helpers.vim
spec/support/test/strategy.vim

This PR fixes (I hope!) #263.
`From :h autoload`:
```
Using an autoload script 
autoload E746
This is introduced in the user manual, section 41.15.
Using a script in the "autoload" directory is simpler, but requires using
exactly the right file name.  A function that can be autoloaded has a name
like this: 
:call filename#funcname()
When such a function is called, and it is not defined yet, Vim will search the
"autoload" directories in 'runtimepath' for a script file called
"filename.vim".  For example "~/.vim/autoload/filename.vim".  That file should
then define the function like this: 
function filename#funcname()
echo "Done!"
endfunction
The file name and the name used before the # in the function must match
exactly, and the defined function must have the name exactly as it will be …
```

Move test strategies to the file with a proper name

---

README.md
VimFlavor
autoload/test/viml/themis.vim
doc/test.txt
plugin/test.vim
spec/fixtures/themis/math.vim
spec/themis_spec.vim

This adds the [`themis`](https://github.com/thinca/vim-themis) runner. I've punted on adding `nearest` support because it will be a little complicated, seeing as it will have to convert a line number to the surrounding themis test function name. For now it just runs the whole file for both `file` and `nearest`.

Add support for vim-themis

---

plugin/test.vim

The VSpec `test_file` function trumps the Themis one, since they both
check the `.vim` extension. This puts `Themis` first, since it is a more
specific check.
This is a quick followup to https://github.com/janko-m/vim-test/pull/269. Sorry for the noise.

Put Themis before VSpec in runner ordering

---

autoload/test/javascript/jest.vim
spec/jest_spec.vim

The original order would run something like
```
jest $FILE -t $NAME
```
With custom options, this can cause issues. For example:
```
jest --reporters some-reporter $FILE
```
jest attempt to use a reporter that matches the test filename.
This change uses the `--` before the input files to make them work
properly with custom and derived arguments.
```
jest --reporters some-reporter -t $NAME -- $FILE
```

Improve argument order for jest named testing

---

README.md
autoload/test/strategy.vim
doc/test.txt

This adds a `vimterminal` strategy which uses the Vim8/MacVim terminal.  
Relates to #282

Add Vim8 terminal strategy

---

README.md
autoload/test.vim
doc/test.txt

This PR adds an option to disable alternate file integration.
There are a few reasons why I don't like alternate file integration. One of them is that I use heavily lazy-loaded and customized versions of vim-rails and projectionist to boost vim start-up times. Which makes vim-test bug, and since it is an independent plugin, it should not.

Add an option to disable alternate file integration

---

README.md
autoload/test/strategy.vim
doc/test.txt

This introduces a new strategy, `make_bang` which uses `:make!` instead
of `:make` which differs in behavior by *not* jumping to the first error
if applicable.
I think I hit all the places these are documented, if not let me know.

Add :make! strategy

---

autoload/test/javascript/jest.vim
spec/jest_spec.vim

It is possible that jest is configured to run coverage checks when running the tests (via the `collectCoverage` setting). This PR disables coverage checking when running a subset of the file since it isn't possible to pass the coverage checks.
We may want to consider disabling coverage checks all-together since Jest's coverage checking would likely breakdown for people with coverage expectations below 100%, anyway. I figured, however, I would leave the existing behaviour intact since it is providing some benefit in the 100% case. I wouldn't be opposed to removing it entirely, though, since it shaves off about 200ms per-test-run on my machine. Thoughts?

jest: no coverage checks when running subset of test for a file

---

README.md
autoload/test/ruby/rspec.vim

This allows running tests using spring when the binstubs are not
generated with spring, which is the case in projects where spring causes
many problems and it's not enabled by default.
This is a quick solution that I've been using, which might make sense to others. What I'd really like instead is a runner that could read configuration from projections https://github.com/janko-m/vim-test/issues/297

Add spring bin detection to rspec runner

---

README.md
autoload/test.vim
doc/test.txt

If `test#enabled_runners` is set, only runners from that list will be
loaded.
It turns out using the namespace for the runner name makes the code simpler.
As discussed on #300

Add option to select which runners to use

---

autoload/test/csharp.vim

This PR adds the missing flags argument in the `substitute` command that only seems to be problematic in windows. The reason I probably missed this is all tests were run on WSL on windows 10 and passed. I was even able to run actual commands in a dotnet project. However, moving over to windows I get the error below that is fixed with this PR, I really wanted to create a test against the csharp.vim file that I could run on windows, but I could not get vim-flavor to run on windows.

fix(csharp): add missing flag arg in substitute cmd

---

README.md
autoload/test/scala.vim
autoload/test/scala/sbttest.vim
doc/test.txt
plugin/test.vim
spec/fixtures/sbt/FixtureSuite.scala
spec/fixtures/sbt/FixtureTest.scala
spec/fixtures/sbt/FixtureTestSuite.scala
spec/fixtures/sbt/SuiteFixture.scala
spec/fixtures/sbt/TestFixture.scala
spec/fixtures/sbt/whatever_suite_smth.scala
spec/fixtures/sbt/whatever_test_smth.scala
spec/sbttest_spec.vim

Hey janko-m,
First of all, thank you for the brilliant work, I am a huge fan, and use vim-test regularly to test my python, ruby and java!
Should you choose to include my contribution for scala testing through sbt, it would be my greatest pleasure.
I tested the solution, and it works fine for me, but as scala imposes way less formatting restrictions compared to java tests for instance, it is hard to create a file pattern regex to match all possible cases. If (when) I find a better one, I will definitely let you know.
Also, I am mostly using maven as scala is a mixin, rather than my primary tool. I will cut some time in the future to attach maven test to scala as well.
Thank you once again, 
with my best wishes, 
Alex T

Add minimal scala support

---

autoload/test/javascript/jest.vim
spec/jest_spec.vim

The jest runner was disabling coverage under some test-run scenarios but not others. Keep things consistent by always disabling coverage.

jest: make consistent by disabling coverage everywhere

---

README.md
autoload/test/strategy.vim
doc/test.txt

This PR adds a way to configure the terminal position for vim's built-in terminal.
It'd also add the new test#vim#term_position variable which IMHO is redundant since the same-ish variable exists for neovim. 
Personally I think it would be better to have one test#vim#term_{split,position} variable and use it for both, vim and neovim.
but this decision is up to @janko-m

Add the ability to configure Vim's terminal position

---

autoload/test/strategy.vim

I initially tried to use BufDelete as per the neovim strategy, but it
didn't work. BufLeave works well for me.

vimterminal: switch back to previous window upon exiting the test runner buffer

---

autoload/test/strategy.vim

This make it behave more like the basic strategy.
I'm putting this up for discussion - it might be a bad idea to implement as a default, what do you think? I have found it a helpful shortcut.

vimterminal: quit on <Enter>

---

autoload/test/php/behat.vim
spec/behat_spec.vim
spec/fixtures/behat/normal.feature

First of all: thanks for the work done, great plugin!
The `:TestNearest` command does not handle "Scenario Outline"
I updated the regex to correct that and the specs/fixture for Behat.
I checked the update README and doc checkboxes even if I didn't.
Because there is nothing do add there, no new feature only a bug-fix.

TestNearest handles "Scenario Outline" for Behat

---

doc/test.txt

This just removes an extra `<` in the help file.

Remove superfluous help markup

---

autoload/test/strategy.vim

Small change to use `cmd.exe` to invoke test commands on windows when using vimterminal strategy.

Add support for 'vimterminal' strategy on windows

---

autoload/test/ruby/rails.vim

In #299, spring bin detection to rspec runner was added. This pr adds spring bin detection to rails runner, using the same mechanism. The [documentation](https://github.com/janko/vim-test#ruby) seems to imply that `let test#ruby#use_spring_binstub = 1` works for every ruby runner, but now the option works just for rspec runner.

Add spring bin detection to rails runner

---

autoload/test/base.vim
autoload/test/php/phpunit.vim
spec/fixtures/phpunit/NormalTest.php
spec/phpunit_spec.vim

Hi again,
I don't think you will remember this almost three years old issue https://github.com/janko-m/vim-test/issues/74
But the fix that was proposed was actually a hack that look for the first public method instead of the actual annotation.
It works great most of the time, I mean like 99% of the time!
Unfortunately since PHP7 we are allowed to create what is called anonymous classes.
Short story long, it's a way to create a class wherever we might want, even inside a method.
I faced such a case this afternoon and realized that if my cursor is inside my test method but under the anonymous class the `:TestNearest` command will stop on the public method of the anonymous class and try to gave it as a filter to PHPUnit.
So I propose this PR to correct that unfortunate behavior.
This is a …

Fix phpunit nearest

---

autoload/test/php/phpunit.vim
spec/fixtures/phpunit/NormalTest.php
spec/phpunit_spec.vim

The fix for the ticket #361 
It was only missing on test for this case.
For phpunit the conditions to find a test was a public method with a name starting by "test".
Or the public method right after a phpdoc block containing the tag "@test", in the form:
```php
/**
* @test
*/
```
I just added a new test to take the following case into account:
```php
/** @test */
```
I'm not use to this style so I don't know if it's tolerated to have multiple tags one the same line...
For now it only works for this specific case.
The reason behind that is that I don't think it's a good idea to have multiple tags on the same line, I'm not event sure it's tolerated in phpdoc.
Plus, we got a great tool called Vim which provides folding :D
I added a new test to confirm the error before fixing it.
And I …

[Bugfix - #361] Handles "/** @test */" on one line

---

README.md
autoload/test/python/pytest.vim
spec/fixtures/pytest_pipenv/Pipfile
spec/fixtures/pytest_pipenv/test_class.py
spec/pytest_pipenv_spec.vim

[pipenv](https://github.com/pypa/pipenv) requires you to run commands with "pipenv run ...". This change prefixes the command if it finds a Pipfile.
I wasn't quite sure how to test this, so let me know if you'd like it done a different way. Also, `pipenv` could work with any of the python runners, but I just added it to the one we use.

Conditionally prefix pytest command with pipenv

---

README.md
autoload/test/base.vim
doc/test.txt
spec/options_spec.vim

references #375 
this will allow users to specify a global option to be set alongside
any granular options for test runners
-  [X] Update the README accordingly

allow a global cli option to be set

---

README.md
autoload/test.vim
autoload/test/base.vim
autoload/test/go/delve.vim
doc/test.txt
plugin/test.vim
spec/delve_spec.vim
spec/fixtures/delve/mypackage/normal_test.go
spec/fixtures/delve/normal_test.go
spec/go_runner_spec.vim

Add support for the Delve test runner for Go that will run `dlv test`
for the identified tests and include breakpoints and tracepoints if
`vim-delve` is also in use.
`vim-test` makes it really easy to run tests in Go programs, but it's
much harder to debug tests. In other languages like Ruby it's relatively
easy because their debuggers are inserted into their normal application
runtimes, but with Go to debug requires executing a different
application with unique parameters. This makes debugging Go tests as
simple as running them, all with vim-test.
Additionally, if vim-delve is in use a user can select breakpoints and
tracepoints within vim, and this change includes pulling in that list of
instructions and includes them in the init setup of dlv. Use of this component
is optional and you …

Add support for the Delve test runner for Go

---

autoload/test/go/delve.vim
spec/delve_spec.vim

Insert a `--` in the dlv test command between the package name and where
test options are supplied.
The `--` is necessary to tell the dlv test command where options for go
test can be supplied vs where the package list start and ends.
When I originally developed the delve runner I had included a `--` and
then removed it thinking it was unnecessary just before I opened the PR
(#385). The test scenarios I'd coded didn't pickup on the options now
being ignored.
Sorry @janko, I didn't pickup on it fast enough before it was merged!

Fix options being appended in delve runner

---

autoload/test/csharp.vim
spec/dotnet_spec.vim
spec/fixtures/dotnet/Tests.cs

It's not uncommon to have tests have a `Task` return type when they're
async, instead of void. With this patch, `:TestNearest` works as
intended when the cursor is inside a test like this:
```
[Fact]
public async Task MyTest()
{
Assert.True(true)
}
```
Before this patch, `:TestNearest` would test the whole file instead.

Recognize `Task` as well as `void` return type

---

autoload/test/scala/sbttest.vim

I could not figure out at all, why my scala test files were always run with `bloop`. I think sbt should also be allowed to run fields with `Spec` in the name

Support `spec` files as well with sbt

---

README.md
autoload/test/haskell.vim
autoload/test/haskell/stacktest.vim
doc/test.txt
plugin/test.vim
spec/fixtures/stack/FixtureSpec.hs
spec/stacktest_spec.vim

Hey, this adds basic support for running tests with stack in haskell.
Please help me out with syntax or anything regarding the vim scripting, as I am pretty new to that.

Add haskell / stack support

---

autoload/test/scala.vim
spec/blooptest_spec.vim
spec/fixtures/sbt/FixtureSpec.scala
spec/fixtures/sbt/WordSpec.scala
spec/sbttest_spec.vim

This adds test for a testing style that was added a while ago, the `WordSpec` style and adds support for the commonly used `FlatSpec` style.
- [x ] Add fixtures and spec when implementing or updating a test runner

Add support for more scalatest styles

---

autoload/test/haskell.vim

If there were more semicolons on the right the `TeastNearest` could have not the correct match eg matching the whole line:
```haskell
it "inserts into a list" $ insert "A" ["B"] `shouldBe` ["A", "B"]
```
instead of only the `it` block

Improve haskell regext to stop matching on "

---

README.md
autoload/test/strategy.vim
doc/test.txt

[Shtuff] is a tool to allow any terminal to become a remote listening terminal. This is a custom strategy I've had for awhile now, but a few others have started using it so I figured it was time to see if I could get it merged in!
[Shtuff]: https://github.com/jfly/shtuff

Add shtuff as an available strategy

---

autoload/test/php/codeception.vim
autoload/test/php/dusk.vim
spec/codeception_spec.vim
spec/dusk_spec.vim

This is similar to #227 that I submitted a couple years ago, but this time it's for Codeception and Dusk. I recently worked on a project with Codeception and was reminded how annoying it is without this regex :)

Codeception and Dusk regex

---

README.md
autoload/test/strategy.vim
doc/test.txt

[Slimux](https://github.com/esamattis/slimux) is yet another plugin to integrate Vim and tmux.
A note about using `command` or `pretty_command`.
When using `pretty_command` with the `preserve_screen` option enabled, the working environment looks like this:
So in order to remove the `echo` part in this situation, I've decided to use `command` when the `preserve_screen` option is enabled. Maybe the same can be applied to other tmux strategies, but since I'm not so familiar with them, I haven't changed any of them.
Of course, I can change it to a more suitable behaviour if needed :wink:.
P.S. I'm new to Vimscript so maybe the condition `if exists('g:test#preserve_screen') && !g:test#preserve_screen` could be simplified. Feel free to correct me! :smile:
P.P.S. I haven't seen any tests for any …

Add Slimux strategy

---

README.md
autoload/test/python/mamba.vim
doc/test.txt
plugin/test.vim
spec/fixtures/mamba/normal_spec.py
spec/mamba_spec.vim

This adds support for the python "Mamba" BDD test runner.
https://nestorsalceda.com/mamba/
Note: The mamba test runner doesn't support running a single test by line number or pattern, it depends on explicit tags or 'fit' style focus. So, this works similar to the busted test runner, where it will still run the whole file for TestNearest.

Add support for python mamba test runner

---

autoload/test/viml/testify.vim
spec/testify_spec.vim

Added support for running nearest tests in testify so ported that to vim-test.

Add support for TestifyNearest

---

autoload/test/swift.vim
spec/fixtures/swiftpm/Tests/VimTestTests/VimTestFinalPublicTests.swift
spec/fixtures/swiftpm/Tests/VimTestTests/VimTestPublicFinalTests.swift
spec/fixtures/swiftpm/Tests/VimTestTests/VimTestPublicTests.swift
spec/swiftpm_spec.vim

Adds support for test classes that are public, public final or final
public. While rare it is allowed for test classes to have these
modifiers.
~- [ ] Update the README accordingly~ n.a.
~- [ ] Update the Vim documentation in `doc/test.txt`~ n.a.
Fixes https://github.com/janko/vim-test/issues/419

Support more class modifier keywords

---

README.md
doc/test.txt

It took me a little while to find https://github.com/janko/vim-test/pull/309 but this feature is already included so it might make sense to document it! I also updated the `doc/test.txt` file to keep it in sync with the README

Update readme to demonstrate vertical split pane

---

bin/kitty_runner

Fixes the kitty runner script so that it's Posix compliant and works on
Gnu/Linux systems.
I just ran the script through shellcheck [1] and followed its
directions.
- [1] https://www.shellcheck.net/
I don't believe there's any necessary doc changes.

Fix kitty runner script

---

autoload/test/shell/bats.vim
spec/bats_spec.vim
spec/fixtures/bats/normal.bats

---
Currently for shell#bats tests, TestNearest are always treated as TestFile. This adds support for TestNearest in shell bats files.

Add support for TestNearest for shell#bats

---

autoload/test/elixir/exunit.vim
spec/exunit_spec.vim

Running mix test with line numbers only selects tests if the line
contains a test block.  The default position for alternative file is
line 1 which generally contains the module, resulting in no tests being
selected.
$ mix test test/example_test.exs:1
Excluding tags: [:test]
Including tags: [line: "1"]
Finished in 0.04 seconds
1 test, 0 failures, 1 excluded

Fix TestNearest alternative with exunit

---

README.md
autoload/test/strategy.vim
doc/test.txt

I would be happy to add tests for this with some guidance. I didn't see any for `AsyncRun` though.
[`pretty`](https://github.com/janko/vim-test/compare/master...webdavis:asyncrun_background?expand=1#diff-52fe4cbf4297c73b5a08849fdfa5eb1cR46) removes escape characters added by `AsyncRun`.
[`status`](https://github.com/janko/vim-test/compare/master...webdavis:asyncrun_background?expand=1#diff-52fe4cbf4297c73b5a08849fdfa5eb1cR39) prepends `Success` or `Failure` to the test for easy feedback. That way the user knows to open the quickfix when a test fails.
skywind3000/asyncrun.vim#178 makes this possible.

Add AsyncRun background variation

---

README.md

The option for hiding the terminal was changed from `-open=0` to `-silent`. I forgot to update the readme after the change was made. Oops.

Fix readme for asyncrun_background

---

autoload/test/java/maventest.vim

The `testfile_import` isn't being used anywhere else in the repo. While this works as a terse way to express the package to be tested — less code — the verbose nature of `[package '.' filename]` reads clearer

Remove unused variables

---

README.md
autoload/test/strategy.vim
doc/test.txt

Add strategy for [vim-tmuxify](https://github.com/jebaum/vim-tmuxify) - yet another plugin to integrate vim with tmux.
Note: I did not use internal pretty command to avoid logging long commands in history. I used `C-u C-l C-u` for screen clear.
Please help me to review it. Thanks.

Add tmuxify strategy

---

autoload/test/strategy.vim

`tmuxify#pane_send_raw` send keys as single to pane, in some program
like `less` it can understand these keys. However, tmux in copy mode
does not understand it.
Please help me to review this PR. Thanks.

Tweak tmuxify strategy a bit

---

autoload/test/rust/cargotest.vim
spec/cargotest_spec.vim
spec/fixtures/cargo/src/nomod.rs
spec/fixtures/cargo/src/somemod_test.rs

Added support when there is no `mod` defined or if the mod name is `test` instead of `tests`
---

fix cargotests run from /tests

---

autoload/test/php/pest.vim

This pull request addresses the link used for the pest documentation.

fix: link to pest website

---

.travis.yml
autoload/test.vim
autoload/test/base.vim
autoload/test/elixir/exunit.vim
autoload/test/go/ginkgo.vim
autoload/test/javascript/ava.vim
autoload/test/javascript/jasmine.vim
autoload/test/javascript/karma.vim
autoload/test/javascript/mocha.vim
autoload/test/perl/prove.vim
autoload/test/php/behat.vim
autoload/test/php/codeception.vim
autoload/test/php/dusk.vim
autoload/test/php/kahlan.vim
autoload/test/php/peridot.vim
autoload/test/php/pest.vim
autoload/test/php/phpspec.vim
autoload/test/php/phpunit.vim
autoload/test/python/mamba.vim
autoload/test/python/pytest.vim
autoload/test/ruby/cucumber.vim
autoload/test/ruby/rspec.vim
autoload/test/shell/bats.vim

The `test#base#no_colors()` function was looking at the global strategy variable, which can be a dictionary when per-granularity strategies was specified. This function doesn't know the granularity, since the `build_args()` runner function is called from `test#execute()`, which doesn't have granularity knowledge (since that function can be called directly via runner commands such as `:RSpec`).
Instead of requiring runners to call into our function for determining whether coloring can be used, we change the code to determine this before calling `build_args()`, and then just pass the boolean value into the function. At that point the strategy has already been resolved, so we can just use it right there and then.
I didn't find a way in VimScript to check how many arguments a function …

Fix coloring flag not working on GUI with granular strategies

---

autoload/test/php/phpunit.vim

This resolves #424 with a simpler solution of just using paratest as the phpunit runner executable if present

Use paratest as the phpunit executable if present

---

autoload/test/erlang/eunit.vim

There's unused script-local function in eunit.vim.

Remove dead code in EUnit runner

---

autoload/test/php/phpunit.vim
spec/paratest_spec.vim
spec/phpunit_spec.vim

This fixes the following issue:
> when executing `TestNearest` now throws `Option --filter is not implemented for non functional mode` because of paratest.
_Originally posted by @vivoconunxino in https://github.com/vim-test/vim-test/pull/471#issuecomment-636066013_

Bugfix for ParaTest nearest

---

README.md
doc/test.txt

Previously, the documentation omitted the protocol for kitty's port, which silently broke the strategy.
Kitty splits the listen-on port by ':', which you can see here:
https://github.com/kovidgoyal/kitty/blob/a0d6445dda1a466b6be7916d2264c55a2960e13c/kitty/utils.py#L382
We need to set `KITTY_LISTEN_ON=unix:/tmp/mykitty` to prevent an argument error a bit further down from this line.
- [NA] Add fixtures and spec when implementing or updating a test runner
- [✓] Update the README accordingly
- [✓] Update the Vim documentation in `doc/test.txt`

Fix readme for kitty strategy

---

README.md
doc/test.txt

The previous documentation for kitty assumed launching via commands.
When using kitty.conf, the logistics are a bit different. This updates
the documentation for using `kitty.conf` as well.
- [NA] Add fixtures and spec when implementing or updating a test runner
- [✓] Update the README accordingly
- [✓] Update the Vim documentation in `doc/test.txt`

Add docs for using kitty via kitty.conf

---

autoload/test/strategy.vim

Previously, if a script existed in a directory whose path contained parentheses,
any strategies relying on `execute_script` would silently fail because the script path
was not escaped.
This fixes the issue by wrapping the path with `shellescape`.
- [NA] Add fixtures and spec when implementing or updating a test runner
- [NA] Update the README accordingly
- [NA] Update the Vim documentation in `doc/test.txt`

Fix exec when script path needs escaping (#482)

---

autoload/test/php/phpunit.vim
spec/phpunit_spec.vim

Remove logic for using artisan test in PHPUnit runner as per https://github.com/vim-test/vim-test/issues/445#issuecomment-646032763 closes #445

Remove logic for using artisan test in PHPUnit runner

---

doc/test.txt

I found an old url in help file, so I fixed it.

doc: Update help file to replace old url references with new url

---

autoload/test/csharp/dotnettest.vim
spec/dotnet_spec.vim

I ran into issues with the current dotnet test runner which didn't allow me to use test nearest and this is a quick fix for it
- [X ] Add fixtures and spec when implementing or updating a test runner
- [X ] Update the README accordingly
- [X ] Update the Vim documentation in `doc/test.txt`

Fixs dotnet test nearest

---

README.md
autoload/test/javascript/ava.vim
autoload/test/javascript/cucumberjs.vim
autoload/test/javascript/cypress.vim
autoload/test/javascript/denotest.vim
autoload/test/javascript/intern.vim
autoload/test/javascript/jasmine.vim
autoload/test/javascript/jest.vim
autoload/test/javascript/karma.vim
autoload/test/javascript/lab.vim
autoload/test/javascript/mocha.vim
autoload/test/javascript/ngtest.vim
autoload/test/javascript/reactscripts.vim
autoload/test/javascript/tap.vim
autoload/test/javascript/webdriverio.vim
spec/fixtures/js_multiple/__tests__/normal-test.js
spec/fixtures/js_multiple/package.json
spec/maventest_spec.vim
spec/specify_js_runner_spec.vim

Test runner detection for JavaScript works by checking which runner is listed in the package.json dependencies. If you have globally installed the runner make sure it's also listed in the dependencies. And now you can specify a runner when hava multiple runners listed in package.json dependencies. 
```vim
let g:test#javascript#runner = 'jest'
```
and fix a warning
not ok 16 - Maven Junit3 multimodule tests runs a test suite with user provided options
{example}，第 4 行
Vim(call):E488: Trailing characters:
spec/maventest_spec.vim .......... Failed 1/28 subtests

Javascript runner can be specified when package.json has multiple runners

---

autoload/test/rust/cargotest.vim
spec/cargotest_spec.vim
spec/fixtures/cargo/src/lib.rs

Regular Rust tests look like this...
#[test]
fn foo_test() {
}
...while async Tokio tests look like this.
#[tokio::test]
async fn foo_test() {
}

cargotest: Add support for async tokio tests

---

autoload/test/rust/cargotest.vim
spec/cargotest_spec.vim
spec/fixtures/cargo/src/lib.rs

Added support for [rstest](https://github.com/la10736/rstest)
Note: Removed the `\]` on the pattern check as these attributes can be multi-line

cargotest: Add support for rstest

---

README.md
autoload/test/python/pyunit.vim
spec/pyunit_pipenv_spec.vim

This change prefixes the pyunit command with 'pipenv run' if it
finds a Pipfile.

Conditionally prefix pyunit command with pipenv

---

autoload/test/rust/cargotest.vim
spec/cargotest_spec.vim
spec/fixtures/cargo/crate/src/main.rs

Before, if you ran tests in `main.rs`, it would invoke `cargo test main::` and not find any tests, but I don't think typically you will actually have a `main` module in `main.rs`.

Fix cargo test invocation for main.rs

---

autoload/test/base.vim

Test runners that provide build_args() taking one argument cannot be used in Vim before 8.0.1423 (and Neovim, #505).
This change adds workaround for Vim (and Neovim) versions that fail to caught an exception thrown from return statement (see vim/vim#2483).

Avoid uncaught exception in test#base#build_args()

---

README.md
autoload/test/ruby/minitest.vim
spec/fixtures/minitest/test_spec.rb
spec/minitest_spec.vim

I'm using (and loving, thank you!) vim-test in an RSpec based Ruby project. Everything was working great until I started trying to test a `Test` class. Because my class name is `Test`, the corresponding RSpec file name is `test_spec.rb`. When I attempt to run the RSpec tests inside this file, vim-test attempts to run Minitest instead of RSpec. This is understandable, as usually Minitest files have `test` in the name whereas RSpec files have `spec` in the name, but in this case my valid RSpec file has both `test` and `spec`.
This PR updates the Minitest file pattern regex to ignore a file starting with 'test' if it also ends with 'spec.rb'. I've added a new test fixture and unit test and the existing unit tests still pass.
Make sure these boxes are checked before submitting your pull …

Minitest: don't pick up RSpec files by mistake

---

autoload/test/strategy.vim

----
Right now, floating terminal window will be closed as soon as tests finished if the floaterm's global option `g:floaterm_autoclose` is `1` or `2`. This is not good design since user should be able to see the testing result.
Hence, the PR aims to keep the window opened until user move the cursor.
cc @codeinabox

Update floaterm strategy

---

README.md
autoload/test/strategy.vim
doc/test.txt

This allows users to disable echoing the test command before running it.
- didn't do this because it doesn't affect any one runner. i also didn't see comparable tests for `g:test#preserve_screen`.

Add g:test#echo_command configuration

---

autoload/test/ruby/rails.vim
spec/fixtures/rails-engine/Gemfile.lock
spec/fixtures/rails/Gemfile.lock

Some applications don't use the `rails` gem explicitly and instead
depend on its components separately, such as `activerecord`,
`activesupport`, etc. When this is how an application requires rails, it
causes the test command to use `bin/rake` instead of `bin/rails` causing
tests not to run.
This resolves the issue by checking the `railties` version which should
always be present, even when `rails` isn't.

Replace rails check with railties check

---

autoload/test/java/maventest.vim

Very minor (and probably niche) change. Made the maven directory src/main/java optional such that src/main will also match.
Why would I want this? I hate deep directory structures with no meaning, and since my project is excursively java it was redundant. This tiny regex change shouldn't effect anyone with a normal maven structure, and will make my weird structure compatible with the plugin.

Made maven java dir optional

---

autoload/test/strategy.vim

The `_VimuxHasRunner` has been removed from the vimux codebase.
For this reason, running tests multiple times will result in the
following error:
Error detected while processing function test#run[26]..test#execute[22]..test#shell[19]..test#strategy#vimux:
line    2:
E117: Unknown function: _VimuxHasRunner
E15: Invalid expression: exists('g:VimuxRunnerIndex') && _VimuxHasRunner(g:VimuxRunnerIndex) != -1
Error detected while processing function test#run[26]..test#execute[22]..test#shell[19]..test#strategy#vimux:
line    2:
E117: Unknown function: _VimuxHasRunner
E15: Invalid expression: exists('g:VimuxRunnerIndex') && _VimuxHasRunner(g:VimuxRunnerIndex) != -1

Update the vimux strategy

---

README.md
autoload/test/strategy.vim
doc/test.txt

Resolves #577 
Added new options `test#neovim#start_normal` and `test#basic#start_normal` which allow not switching to insert mode when opening a terminal in Neovim.

Allow starting neovim term in normal mode

---

autoload/test/kotlin.vim
autoload/test/kotlin/gradletest.vim
spec/fixtures/gradle/kotlin/gradle_plain/CalculationTest.kt
spec/fixtures/gradle/kotlin/gradle_plain_kotlin_dsl/CalculationTest.kt
spec/kotlin_gradletest_spec.vim
spec/kotlin_gradletest_spec_koltin_dsl.vim

In Kotlin, test function names can be surrounded by backticks. https://todd.ginsberg.com/post/kotlin-function-names/
This PR would update the regex (to match any character between backticks) and replace the backticks in the gradle command by `"`.
README and docs updates not needed.

Enable backtick surrounded test names in Kotlin

---

autoload/test/javascript/cucumberjs.vim
spec/cucumberjs7+_spec.vim
spec/fixtures/cucumberjs7+/features/normal.feature
spec/fixtures/cucumberjs7+/features/step_definitions/steps.js
spec/fixtures/cucumberjs7+/package.json

The cucumber-js module changed from `cucumber` to `@cucumber/cucumber`
in version 7+.
- [X ] Add fixtures and spec when implementing or updating a test runner

Add support for cucumber-js 7+

---

autoload/test/dart/fluttertest.vim
spec/fixtures/fluttertest/widgets_test.dart
spec/fluttertest_spec.vim

When the test description is very long dart formatter moves the description to a separate line. Additional regex help match this line, if it is long enough (I arbitrary chosen more than 50 chars length).
It fixes #602

Pick long name Flutter test with TestNearest command

---

autoload/test/go.vim
spec/delve_spec.vim
spec/fixtures/delve/mypackage/normal_test.go
spec/fixtures/delve/normal_test.go
spec/fixtures/gotest/mypackage/normal_test.go
spec/fixtures/gotest/normal_test.go
spec/fixtures/richgo/mypackage/normal_test.go
spec/fixtures/richgo/normal_test.go
spec/gotest_spec.vim
spec/richgo_spec.vim

In Go, test function name rule is to begin with `Test`.
Actually, `Testテスト` is testable.
```
> go test -v . --run Testテスト
=== RUN   Testテスト
--- PASS: Testテスト (0.00s)
PASS
ok      github.com/lunarxlark/test     0.243s
```

fix test function pattern for Go

---

autoload/test/haskell/stacktest.vim
spec/stacktest_spec.vim

This PR allows overriding the test command for Haskell's `stack`. Specifically, it allows you to use `test .` as the default command, which works better in multi-package stack projects.

Allow configuring stack test command

---

autoload/test/base.vim
autoload/test/csharp.vim
autoload/test/csharp/dotnettest.vim
spec/dotnet_spec.vim
spec/fixtures/dotnet/FileNamespaceTests.cs

Rework dotnettest. Now it uses right filters and support file namespaces.

fix: dotnettest search

---

autoload/test/go/ginkgo.vim
spec/fixtures/ginkgo/normal_test.go
spec/ginkgo_spec.vim

Thank you so much for this AMAZING plugin!
This pull request updates the Ginkgo autoload to be compatible with v2.
Specifically, it:
- Removes `--focus` in favour of `--focus-file`, and
- Removes `--regexScansPath`, as `--focus-file` and `--skip-file` have
deprecated it.
Signed-off-by: Carlos Nunez <13461447+carlosonunez@users.noreply.github.com>

Update to Ginkgo v2

---

autoload/test/rust/cargotest.vim
spec/cargotest_spec.vim
spec/fixtures/cargo/crate/src/lib.rs

In case there are other prefixes, used an arbitrary word pattern rather
than hardcoded string.

fix(rust): support actix rt tests

---

autoload/test/go/gotest.vim
spec/fixtures/gotest/build_tags_test.go
spec/gotest_spec.vim

When current file's got build tag constraints, by default it may not be
compiled by `go test`. This commit tries to parse the +build tags [1]
and add `-tags=foo,bar` to the command line.
The new go:build [2] is not supported since it's quite troublesome to
process. Users of Go 1.17+ can have both go:build and +build in a file
as long as they are consistent, or manually `:TestFile -tags=foo,bar`.
[1] https://pkg.go.dev/cmd/go@go1.16.15#hdr-Build_constraints
[2] https://pkg.go.dev/cmd/go@go1.18#hdr-Build_constraints

Support Go +build tags

---

autoload/test/php/pest.vim
spec/fixtures/pest/PestTest.php
spec/pest_spec.vim

I've been using [this plugin](https://github.com/milroyfraser/pest-plugin-gwt) with pest but the patterns don't support it.
So this PR allows matching on the extra pattern.

Add support for Pest GWT plugin

---

autoload/test/php/codeception.vim
spec/codeception_spec.vim

Extend detection for codeception test file.
Respect codeception.dist.yml beside codeception.yml.
As documented by https://codeception.com/docs/reference/Configuration#Configuration-Templates-distyml

Add support for codeception .dist.yml

---

autoload/test/go.vim
autoload/test/go/gotest.vim
autoload/test/go/richgo.vim
spec/fixtures/gotest/normal_test.go
spec/fixtures/richgo/normal_test.go
spec/gotest_spec.vim
spec/richgo_spec.vim

Makes `:TestNearest` work with `t.Run()` subtests in golang.
Since `-run` takes a regex, there's a need to escape characters. I could use some guidance with tests for for those, as it is a bit nasty. 😅
---

Support go subtests

---

autoload/test/go/gotest.vim
autoload/test/go/richgo.vim
spec/fixtures/gotest/normal_test.go
spec/fixtures/richgo/build_tags_test.go
spec/fixtures/richgo/normal_test.go
spec/gotest_spec.vim
spec/richgo_spec.vim

- Fixes an issue where tests with `(` or `)` in their description would not be picked up correctly
- Reuse `gotest` implementation in `richgo` - they are essentially the same
---

Go subtests escape more characters

---

README.md
autoload/test.vim
doc/test.txt

Hopefully this could be helpful for somebody else.
I'm using https://github.com/rgroli/other.nvim and wanted to integrate with it.
Not sure if this needs a test, my first time touching vimscript really :shushing_face: 

Allow for custom alternate file function

---

autoload/test/strategy.vim

Fixes a bug introduced in a5b122e8c5eb47db5a034908172ccbee44f4e520 where it will crash due to unknown variable

Fix typo in variable name

---

autoload/test/java/maventest.vim
spec/fixtures/maven/sample_maven_junit5_mvnw_project/.gitignore
spec/fixtures/maven/sample_maven_junit5_mvnw_project/.mvn/wrapper/maven-wrapper.properties
spec/fixtures/maven/sample_maven_junit5_mvnw_project/mvnw
spec/fixtures/maven/sample_maven_junit5_mvnw_project/pom.xml
spec/fixtures/maven/sample_maven_junit5_mvnw_project/src/main/java/org/vimtest/App.java
spec/fixtures/maven/sample_maven_junit5_mvnw_project/src/test/java/org/vimtest/TestApp.java
spec/maventest_spec.vim

Although groovy tests support mvnw executable, java tests have not supported it.
When the vim-test can find the mvnw executable, it will run the test with mvnw.
-----

Support executing maven wrapper on Java tests

---

autoload/test/strategy.vim

In #578, starting in normal mode was introduced, but due to a typo, it does not work for basic strategy. This PR fixes that.

Fix normal mode start for basic strategy

---

autoload/test/go/ginkgo.vim
spec/fixtures/ginkgo/normal_test.go
spec/ginkgo_spec.vim

1. ginkgo v2 support args `--focus`.
Ref: https://github.com/onsi/ginkgo/blob/v2.1.4/types/config.go#L282-L283
```
➜  ~ ginkgo version
Ginkgo Version 2.1.4
➜  ~ ginkgo help run | grep -A3 -- '--focus'
--focus [string]
If set, ginkgo will only run specs that match this regular expression. Can
be specified multiple times, values are ORed.
--skip [string]
```
2. Use parameter `--focus-file` for `name` will not match any case.
3. Reproduce and compare
```
➜  cd spec/fixtures/ginkgo/
➜ ginkgo git:(master) ✗ go mod init test
go: creating new go.mod: module test
go: to add module requirements and sums:
go mod tidy
➜  ginkgo git:(master) ✗ go mod tidy
go: finding module for package github.com/onsi/ginkgo
go: finding module for package github.com/onsi/ginkgo/v2
go: finding module for package …
```

fix: Ginkgo call `Nearest` failures

---

autoload/test/elm/elmtest.vim
spec/elmtest_spec.vim

Elm runner does not cover the case that users install elm executables as their local dependecies.
This PR adds it.
---

Uses elm-test in node_modules if available

---

bin/kitty_runner

Addition of non-standard function declaration broke kitty strategy from commit d7008abc25c5593e3d204d5b9508645fd40187e8 onward. This standardizes the function declaration and cleans up some warnings listed in [ShellCheck](https://www.shellcheck.net/).

Fix non-standard function declaration within kitty strategy and cleanup shellcheck warnings

---

autoload/test/go.vim
spec/fixtures/gotest/normal_test.go
spec/fixtures/richgo/normal_test.go
spec/gotest_spec.vim
spec/richgo_spec.vim

Right now, when attempting to `:TestNearest` a nested test, such as:
```go
function TestSomething() {
t.Run("foo", function() {
t.Run("bar", function() {
// execute :TestNearest here
})
})
}
``` 
vim-test will run `TestSomething/foo`, while it should run `TestSomething/foo/bar`. 
This PR makes vim-test pick up nested tests correctly.
---

Make `:TestNearest` work with nested tests in golang

---

autoload/test/javascript/cypress.vim
spec/cypress_spec.vim
spec/fixtures/cypress/integration_tests/normal.cy.js
spec/fixtures/cypress/integration_tests/normal.test.js

I use cypress in my workplace and we've recently moved to the default naming
convention specified by some cypress config.
This PR moves vim-test to support this file naming structure.
- Support .cy.{js,jsx,coffee} file suffix type
- Adds fixtures for cy and test file suffix types
- Adds coverage for cy and test file types

Support default cypress extension type

---

autoload/test/strategy.vim

Currently, running `TestNearest -strategy=toggleterm` on the [Kotlin backticks method ](https://kotlinlang.org/docs/coding-conventions.html#names-for-test-methods)fails because `TermExec cmd=""` is using double quotes in the command. According to the [documentation](https://github.com/akinsho/toggleterm.nvim/blob/main/doc/toggleterm.txt) for TermExec , we have to use quotes. Using the double quotes in this case cause the command to be prematurely terminated when a test name containing double quotes is encountered. This results in all tests in the class being run instead of just the nearest test.
To resolve this issue, I just change the double quotes to single quotes at the start of the command. This will allow the …

Enable toggle term to execute kotlin backticks test methods

---

autoload/test/python/pyunit.vim
spec/pyunit_pipenv_spec.vim
spec/pyunit_spec.vim

This is necessary since some platforms such as MacOS have no explicit alias for python.

Python: Use explicit Python3 in invocation

---

README.md
autoload/test/rust/cargotest.vim
doc/test.txt
spec/cargotest_spec.vim

- [√] Add fixtures and spec when implementing or updating a test runner
- [√] Update the README accordingly
- [√] Update the Vim documentation in `doc/test.txt`
usage: add to .vimrc
```vim
let test#rust#cargotest#test_options = { 'nearest': ['--', '--nocapture', '--exact'], 'file': [] }
```

add `g:test#rust#cargotest#test_options` for custom cargo test_options

---

autoload/test/csharp.vim

When running one of these commands for csharp in windows it was complaining that s:slash variable was not set - I think it might be because I am on windows and not using a terminal that equates to either cmd.exe or powershell, in this case the pack was not working so I have set the slash to be a forward slash unless you are running a specific terminal on windows
Fixes - https://github.com/vim-test/vim-test/issues/731

bugfix(csharp) - fixing default slash for windows

---

autoload/test/php/phpunit.vim
spec/sail_spec.vim

The current behaviour in vim-test is to use Laravel Sail whenever `vendor/bin/sail` exists, however, this comes pre-installed in fresh Laravel applications these days and does not mean the user will actually be using Docker for local development.
Currently users will get the following error when using vim-test in a fresh Laravel application:
Users that wish to use Sail would typically run `php artisan sail:install` which will create their `docker-compose.yml` file.
This PR updates vim-test to only use Sail when `docker-compose.yml` (or `docker-compose.yaml`) also exists in addition to `vendor/bin/sail`.

Only use Sail when it's configured

---

README.md
autoload/test/zig/zigtest.vim
doc/test.txt
plugin/test.vim
spec/fixtures/zig/normal.zig
spec/zig_spec.vim

I'm new to both vimscript and zig, so I mostly copied this from the `bats` implementation. From what I can gather, [there isn't a way to use a pattern to run a single test with `zig test`, so there's a chance multiple tests match](https://github.com/ziglang/zig/issues/13524), but this seems close enough for now?
For running the whole suite, seems like there's a pattern to define a test step in `build.zig`, [(1)](https://github.com/mattnite/gyro), [(2)](https://github.com/kooparse/zalgebra), so that's how I decided to implement `TestSuite`.
Either way, thanks for considering! Let me know if I can make any changes.

Add Zig Support

---

autoload/test/javascript/jest.vim
spec/jest_spec.vim
spec/specify_js_runner_spec.vim

This resolves #745 by removing the logic for setting the no coverage option on Jest tests

feat: remove logic for setting the no coverage option on Jest tests

---

autoload/test/javascript/ava.vim
spec/ava_spec.vim
spec/fixtures/ava/test/normal.ts

- [-] Update the README accordingly
- [-] Update the Vim documentation in `doc/test.txt`
Brings AVA runner up to parity with Jest and other javascript runners.
It appears to me that the README and test.txt do not go into a level of detail where this change can be documented meaningfully. It is more of a bugfix catching the runner up to what a consumer would ordinarily expect from current documentation.

Enable AVA.js test detection in typescript files

---

autoload/test/zig.vim
autoload/test/zig/zigtest.vim
spec/zig_spec.vim

This changes the 'nearest' test type to use `zig test --test-filter`. It kinda goes against the decision made by @bobcats  in https://github.com/vim-test/vim-test/pull/736, which specifically didn't support this because `--test-filter` doesn't allow for regexs and might run more tests than we want.
But I figured: I'd rather run more tests if they match the same name, vs. the whole file all the time.
At least I want this feature, but happy to hear any feedback :)
---

zig: use --test-filter when running nearest test

---

autoload/test/strategy.vim

The `shtuff` strategy did not obey the `g:test#preserve_screen` option. No doc or README update because it already implied that it would be obeyed... No fixture or spec related to `shtuff` to update.

Obey g:test#preserve_screen for 'shtuff' strategy

---

autoload/test/javascript/nx.vim
spec/fixtures/nx/apps/backend/normal-test.js
spec/fixtures/nx/apps/backend/project.json
spec/fixtures/nx/apps/products/normal-test.jsx
spec/fixtures/nx/workspace.json
spec/nx_spec.vim

As mentioned in #633 and addressed in #649, when running tests in an nx environment it needs to reference the project name, (i.e. `nx test <project-name>`). Since #649 was opened, [`nx` has stopped using the `workspace.json`](https://nx.dev/deprecated/workspace-json#) format to list project names. In newer Nx codebases, project directories have a `project.json`file.
This PR adds implementation to identify a project name from either the `project.json` file or `workspace.json` file as implemented in #649.

fix: not recognizing project names when using Nx

---

autoload/test/strategy.vim

As mentioned in #763, pressing `<Enter>` in a vim terminal window closes it, but does not unload the buffer. This causes every test run to leave a lingering buffer behind, polluting the buffer list.
As far as I can tell, using `:bd` instead of `:q` to make sure the buffer is deleted does not have any drawbacks.

fix: delete buffer when closing vimterminal window

---

autoload/test/go/gotest.vim
spec/fixtures/gotest/build_tags_117_test.go
spec/gotest_spec.vim

No updates to the README or Vim documentation are necessary
Go 1.17 added `//go:build` lines as the preferred way over `// +build` lines to specify build tags (see [Release Notes](https://go.dev/doc/go1.17)).
With the changes in this PR, `vim-test` will support both `//go:build` and `// +build` lines.
Fixes #751

support Go 1.17 build tags

---

README.md
autoload/test/strategy.vim
doc/test.txt

Adds a `test#neovim_sticky#reopen_window` option to the Neovim sticky strategy that will open a new split for the terminal if it's buffer was previously hidden.

Add neovim_sticky option to reopen hidden buffer

---

autoload/test/erlang/eunit.vim
spec/eunit_spec.vim
spec/fixtures/eunit/example_tests.erl

This PR allows to run individual test cases with EUnit runner for Erlang.
`--test` flag for `eunit` task is supported by Rebar3 for over a year (since 3.19), and `--generator` was added back in 2018.

Support :TestNearest for EUnit runner

---

autoload/test/clojure.vim
autoload/test/clojure/leintest.vim
spec/fixtures/clojure/math_test.clj
spec/leintest_spec.vim

This PR updates the Clojure test patterns to support a few additional use-cases. The pattern originally only supported tests defined as `(deftest ...`, but with this change now also supports
1. Qualified `deftest` (i.e. `(clojure.test/deftest ...`)
2. [`defspec`](http://clojure.github.io/test.check/clojure.test.check.clojure-test.html#var-defspec)
3. Qualified `defspec`
It also updates the Leiningen test runner to wrap the test name in `shellescape()`, since Clojure supports a number of additional characters that wreak havoc with Bash.

clojure: Expand patterns to support more use-cases

---

README.md
autoload/test/strategy.vim
doc/test.txt

This is a pretty minimal strategy to just send the command to an adjacent wezterm pane.

Add `wezterm` strategy

---

README.md
autoload/test/go/gotest.vim
spec/fixtures/gotest/testify_test.go
spec/gotest_spec.vim

Hi, I  implement the issue https://github.com/vim-test/vim-test/issues/624
and I think the document  is added by PR #694
I hope I can help it.
And It supposes that the user imports "testify/suite" and there is only one general Go test (the test has testing.T) as Test{X}Suite.

feat: support for go stretchr/testify

---

autoload/test/go/gotest.vim
spec/fixtures/gotest/testify_test.go
spec/gotest_spec.vim

In this PR https://github.com/vim-test/vim-test/pull/781 I suppose the user only uses one original Golang testcase
I tried to improve the script to support more complicated situations 
1. run multiple suites
2. mix testify suite and original Golang testcase

feat: support go testify for multiple suite and original testcase

---

autoload/test/ruby/minitest.vim

If you have a strategy that uses `bin/test` to run, it will not match against 'ruby' or 'rake'.
My suggestion is we fall back to ruby when neither is present. While this does presume ruby as the default, the alternative is it not working.
I'd also be happy to make this a configuration option instead if that makes more sense.
**NOTE:** Regarding these checkboxes:
- There are no fixtures or specs for using minitest with ruby in general, just for rake.
- Don't think the README needs to be updated
- I don't see a need for an update in doc/text.txt.

Update minitest.vim to use ruby args by default for when runner name does not contain ruby/rake

---

README.md
autoload/test.vim
doc/test.txt

I wanted to dynamically set the project_root and found the easiest way to do that is by allowing it to be a function. That way I can very flexibly decide where the project root is.

Allow setting a dynamic project_root

---

autoload/test/strategy.vim
doc/test.txt

The `split-pane` command creates a split that's 50% of the screen width when split using `--right`. This may be wider than some preferred. This adds a `split_percent` option to customize the width of the split pane.

Add split pane percent to WezTerm strategy

---

README.md
autoload/test/go/gotest.vim
doc/test.txt
spec/gotest_spec.vim

specifically
-args
Pass the remainder of the command line (everything after -args)
to the test binary, uninterpreted and unchanged.
Because this flag consumes the remainder of the command line,
the package list (if present) must appear before this flag.
https://pkg.go.dev/cmd/go/internal/test#pkg-index
btw, i am not very sure where to write the docs as this is very go specific

Support gotest args

---

README.md
autoload/test/rust/cargonextest.vim
autoload/test/rust/cargotest.vim
spec/cargonextest_spec.vim
spec/cargotest_spec.vim
spec/fixtures/cargo/crate/Cargo.toml

Updates `cargotest` and `cargonexttest` scripts to read `pakage.name` from `Cargo.toml` instead of relying only on the directory name.
Fixes https://github.com/vim-test/vim-test/issues/807
^ doesn't look like it is necessary

Cargo feature/allow named packages

---

autoload/test/php/pest.vim
spec/sail_spec.vim

This PR adds support for running Pest test suites via Laravel Sail automatically.
Sail is already detected for PHPUnit testsuites. This uses the same mechanism.
I have not updated the readme or docs as this feels more like an enhancement than a feature worth documenting.

Run `pest` via `sail` when configured

---

README.md
autoload/test.vim
doc/test.txt

Adds an optional user prompt when executing tests with unsaved files. Also adds documentation for how `autowrite` is handled within vim-test. Fixes #723.
<hr>

Add optional prompt when executing tests with unsaved files

---

autoload/test/strategy.vim

Fixes #824 , bug fix no docs update needed.

Fix neovim_sticky strategy in Linux PowerShell

---

autoload/test/strategy.vim

If `test#neovim#term_position` is set to something like `botright 10` to setup a terminal that is 10 in height and we need to reopen the terminal since it isn't visible, the current `s:neovim_reopen_term()` function doesn't correctly re-open the terminal with the appropriate height. This PR addresses this by running something like `botright 10 new | buffer [bufnr]` which sets the height correctly instead of `botright 10 sbuffer [bufnr]` which doesn't.

Fix term_position usage in s:neovim_reopen_term

---

autoload/test/java/maventest.vim
doc/test.txt
spec/fixtures/maven/sample_maven_junit3_multimodule_project/sample_module2/pom.xml
spec/fixtures/maven/sample_maven_junit5_multimodule_project/pom.xml
spec/fixtures/maven/sample_maven_junit5_multimodule_project/sample_module2/pom.xml
spec/fixtures/maven/sample_maven_junit5_multimodule_project/sample_module2/src/main/java/org/vimtest/App.java
spec/fixtures/maven/sample_maven_junit5_multimodule_project/sample_module2/src/test/java/org/vimtest/AppIT.java
spec/fixtures/maven/sample_maven_junit5_multimodule_project/sample_module2/src/test/java/org/vimtest/AppITCase.java
spec/fixtures/maven/sample_maven_junit5_multimodule_project/sample_module2/src/test/java/org/vimtest/AppTestIntegration.java
spec/fixtures/maven/sample_maven_junit5_multimodule_project/sample_module2/src/test/java/org/vimtest/TestApp.java
spec/maventest_spec.vim

Running a single test or test suite in a multimodule Maven project doesn't work when the test is in a submodule `B` that depends on another submodule `A`. In these cases, we need to add:
- `-am` so Maven (re)builds module `A` as well as `B`, if necessary
- `-Dsurefire.failIfNoSpecifiedTests=false` so the build doesn't fail when the specified test from module `B` doesn't exist in `A` (only in case of running unit tests with surefire)
- `-Dfailsafe.failIfNoSpecifiedTests=false` so the build doesn't fail when the specified test from module `B` doesn't exist in `A` (only in case of running integration tests with failsafe)
If the test is in `A`, these parameters aren't necessary, but it doesn't matter if they're there. If the test is in `B`, Maven fails because it tries to find the test in `A` …

Maven: fix multimodule when one submodule depends on another

---

autoload/test/rust/cargotest.vim
spec/cargotest_spec.vim
spec/fixtures/cargo/crate/src/bin/nestedbin/main.rs
spec/fixtures/cargo/crate/src/bin/nestedbin/somemod.rs
spec/fixtures/cargo/crate/src/bin/somebin.rs

This is a special directory for projects that author multiple binaries. When focusing tests in these directories, `bin::` should be omitted from the module path, and the `--bin` argument should be set to the appropriate binary name (derived from the path).
See:
https://doc.rust-lang.org/cargo/reference/cargo-targets.html#binaries

Fix cargo test handling of `src/bin` files

---

autoload/test/strategy.vim

`[No Name]` buffers are created when we call `s:neovim_reopen_term()` as we call `new` before switching to the terminal buffer. This change calls `bunload` to unload the temporary no name buffer so we don't pollute the buffer list with no name buffers.

Unload no name buffers in s:neovim_reopen_term

---

README.md
autoload/test/strategy.vim
doc/test.txt

Resolves #836 
Small reformatting of previous options docs' for more consistent look.

Add neovim_sticky use_existing flag

---

autoload/test/javascript/jest.vim
spec/jest_spec.vim

Escapes brackets in file/path names when running tests using Jest. Use case is for developers working on NextJS codebases where bracketed folder names are used to group modules.

escape brackets in pathnames when running jest

---

README.md
autoload/test/python/mamba.vim
autoload/test/python/nose.vim
autoload/test/python/pytest.vim
autoload/test/python/pyunit.vim
doc/test.txt
spec/mamba_uv_spec.vim
spec/nose_uv_spec.vim
spec/pytest_uv_spec.vim
spec/pyunit_uv_spec.vim

Fixes #840 
I mostly mimicked https://github.com/vim-test/vim-test/pull/538, but let me know if I need to tweak something.
P.S. I went by grepping `pipenv` and added `uv` in the same places, and I see `pipenv` is supported for more runners than just `pytest` and `djangotest`, or so it seems at least 😅 
P.P.S off-topic, but just wanted to say that it was a pleasure finding this plugin, not just because it's the first one that works, but also because you're really supportive of contributors, so thank you!

Add `uv` support for python runners

---

autoload/test/php/phpunit.vim

The information for the nearest PHPUnit test is printed and triggers a hit-enter prompt in some cases. I don't see the value of this being printed apart for debugging purposes.

Remove useless echo of nearest test info for PHPUnit

---

autoload/test/viml/themis.vim
spec/fixtures/themis/math.vimspec
spec/themis_spec.vim

Themis can use `--target pattern` to filter tests, which can be used as the Nearest position.
This PR only handles "vimspec" style, because in "basic" style (where a test is a vim function) it is unreliable to identify tests by merely pattern searching.
(No need to update README and documentation)

Add Nearest support to vim-themis (vimspec style)
