vim-test/vim-test

README.md, autoload/test/strategy.vim, doc/test.txt
Just swapped to using VTR for my Vim + Tmux integration and missed having support for it in this!
=> Add VimTmuxRunner strategy

autoload/test/javascript/mocha.vim
This update allows the mocha test file regex to match a nested test
directory.
=> Update mocha matching regex

README.md, autoload/test.vim, doc/test.txt, plugin/test.vim
First, thanks for this lifechanging plugin. :smiley: 
This is a simple support for custom strategies (#28) via dict and funcref.
Docs and readme are also updated.
=> Add support for custom strategies

README.md
Hi @janko-m, I was installing your plugin and noticed small typo :)
=> Typo in readme fixed

README.md, autoload/test/php/phpspec.vim, doc/test.txt, plugin/test.vim, spec/fixtures/phpspec/NormalSpec.php, spec/phpspec_spec.vim
Adds support for PHPSpec. All unit tests are passing but needs real world testing.
=> [WIP] PHPSpec support

autoload/test/java.vim, autoload/test/java/maven.vim, plugin/test.vim
This PR adds a Maven runner for Java JUnit tests.
=> Add Maven runner for Java.

README.md, autoload/test/java/maven.vim
Fix a bug introduced during some cleanup.
=> Fix bug with filename computation.

README.md, autoload/test/elixir/espec.vim, doc/test.txt, plugin/test.vim, spec/espec_spec.vim, spec/fixtures/espec/normal_spec.exs
the alternative test framework, inspired by RSpec - [ESpec](https://github.com/antonmi/espec)
=> add Elixir ESpec runner

autoload/test/php/phpunit.vim, spec/fixtures/phpunit/NormalTest.php, spec/phpunit_spec.vim
=> Fixed PHPUnit nearest to handle tests with arguments

autoload/test/go/gotest.vim, spec/fixtures/gotest/mypackage/normal_test.go, spec/gotest_spec.vim
=> Handling when `TestFile` is called on a Go test in a subdirectory

autoload/test/perl/prove.vim, plugin/test.vim
Add support for perl's core [prove](http://perldoc.perl.org/TAP/Harness.html#prove) runner
=> Add support for perl's prove runner

README.md
Clarify that the install instructions are for vim-plug.
=> Install instructions are for vim-plug

autoload/test/javascript/karma.vim, spec/karma_spec.vim
According to http://karma-runner.github.io/1.0/config/configuration-file.html
=> Fix incorrect log level for karma

autoload/test/ruby/rails.vim, plugin/test.vim
Copied mostly from the m test runner.
See also issue #130
=> Adds support for rails 5 test runner

autoload/test/strategy.vim
This PR adds a strategy for the asyncrun plugin.
=> Add asyncrun strategy

README.md, doc/test.txt
- Added link to asyncrun plugin to README
- Added note saying that asyncrun strategy requires AsyncRun plugin
=> Improve documentation about asyncrun strategy

autoload/test/php/behat.vim
=> Look for behat executable in ./vendor/bin/behat

README.md, autoload/test/php/kahlan.vim, autoload/test/php/peridot.vim, autoload/test/php/phpspec.vim, doc/test.txt, plugin/test.vim, spec/fixtures/kahlan/spec/Normal.spec.php, spec/fixtures/peridot/arrayobject.spec.php, spec/kahlan_spec.vim, spec/peridot_spec.vim
This adds basic support for PHP test frameworks Kahlan and Peridot. Handling test nearest is forthcoming.
=> Adds support for PHP test frameworks Kahlan and Peridot

autoload/test/javascript/jest.vim
This original regex is mentioned in the testRegex section package.json example in https://facebook.github.io/jest/docs/en/getting-started.html#using-typescript
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/janko-m/vim-test/190)
=> Use regex similar to jest official doc

README.md, doc/test.txt
=> Update docs to include information about the strategies that use quickfix

autoload/test/javascript/mocha.vim, spec/fixtures/mocha-webpack/outside.js, spec/fixtures/mocha-webpack/package.json, spec/fixtures/mocha-webpack/test/context.js, spec/fixtures/mocha-webpack/test/normal.coffee, spec/fixtures/mocha-webpack/test/normal.js, spec/fixtures/mocha-webpack/test/normal.jsx, spec/mocha-webpack_spec.vim
Check to see if mocha-webpack is installed, if so use it, if not then do usual checks for mocha
=> Use mocha-webpack instead of mocha if it's installed

autoload/test/javascript/jest.vim, autoload/test/javascript/mocha.vim
=> Fix detetion for Mocha and Jest

autoload/test/strategy.vim
Fixes #222 
Inspired by this PR on fugitive: https://github.com/tpope/vim-fugitive/pull/784
=> Fix tabpage ordering for neovim 'basic' strategy

autoload/test/python.vim, spec/fixtures/nose/test_class.py, spec/pytest_spec.vim
Follow-up to https://github.com/janko-m/vim-test/pull/235.
=> Handle unittest.TestCase in Python patterns

README.md, autoload/test/javascript/webdriverio.vim, doc/test.txt, plugin/test.vim, spec/fixtures/webdriverio/package.json, spec/fixtures/webdriverio/test/specs/example.js, spec/fixtures/webdriverio/wdio.conf.js, spec/webdriverio_spec.vim
This adds Webdriver.io support as requested in #225
=> Webdriver.io support

autoload/test/csharp/dotnettest.vim, autoload/test/elixir/espec.vim, autoload/test/elixir/exunit.vim, autoload/test/erlang/commontest.vim, autoload/test/php/behat.vim, autoload/test/python/djangotest.vim, autoload/test/python/pyunit.vim, autoload/test/racket/rackunit.vim, autoload/test/ruby/cucumber.vim, autoload/test/ruby/m.vim, autoload/test/ruby/minitest.vim, autoload/test/ruby/rails.vim, autoload/test/shell/bats.vim, autoload/test/viml/vader.vim
=> Update all file patterns to be POSIX standard

README.md, doc/test.txt
Documentation to accompany the commit 1edd7be495b76f1332a8d6b5c3bb1d2bc5aacd17
=> Document Projectionist integration

README.md, autoload/test/csharp.vim, autoload/test/csharp/dotnettest.vim, autoload/test/csharp/xunit.vim, doc/test.txt, plugin/test.vim, spec/dotnet_spec.vim, spec/dotnet_xunit_spec.vim, spec/fixtures/dotnet-xunit/NestedTests.cs, spec/fixtures/dotnet-xunit/Tests.cs, spec/fixtures/dotnet-xunit/Tests.csproj, spec/fixtures/dotnet-xunit/TestsWithFixture.cs, spec/fixtures/dotnet/NestedTests.cs
This is initial support for the `dotnet-xunit` tool provided by the XUnit framework for C#.
=> [RFC] dotnet-xunit support

autoload/test/python.vim, spec/fixtures/nose/test_class.py, spec/pytest_spec.vim
=> Simplify the Python namespace regular expression

README.md, autoload/test/javascript/ava.vim, doc/test.txt, plugin/test.vim, spec/ava_spec.vim, spec/fixtures/ava/package.json, spec/fixtures/ava/test/normal.js, spec/mocha_spec.vim
This picks up the work done in #148 and updates it to use `has_package`
=> Javascript Ava runner support

autoload/test/php/phpunit.vim, spec/phpunit_spec.vim
https://travis-ci.org/przepompownia/phpunit-filter-example
=> Fix phpunit filter for tests with and without data provider

autoload/test/javascript/karma.vim
With the most recent Jest MR (#280) came TypeScript support. This introduces the same for Karma.
=> Add TypeScript support to Karma test file pattern

autoload/test/csharp.vim
=> fix(dotnet): add logic for backward slash on windows

autoload/test/swift.vim, autoload/test/swift/swiftpm.vim, spec/fixtures/swiftpm/Tests/VimTestRootTests.swift, spec/fixtures/swiftpm/Tests/VimTestTests/VimTestFinalTests.swift, spec/swiftpm_spec.vim
- Syntax for limiting the cases to run has changed
- Improve the quality of the test code a bit
- Improve module recognition
=> Small improvements to swiftpm testing

README.md, autoload/test/strategy.vim, doc/test.txt
=> Add the ability to configuring the Neovim terminal position

autoload/test/python/pyunit.vim
=> fix pyunit problem in windows

autoload/test/python/djangotest.vim
=> Also fix django runner for windows

README.md, autoload/test/java/gradletest.vim, autoload/test/java/maventest.vim, doc/test.txt, plugin/test.vim, spec/fixtures/gradle/MathTest.java, spec/fixtures/gradle/MathTestCase.java, spec/fixtures/gradle/MathTests.java, spec/fixtures/gradle/TestMath.java, spec/gradletest_spec.vim
=> Add support for Gradle

doc/test.txt
Found another one.  I can squash this with the last one if you like.
=> Fix markup in help file

README.md
Update README to comply with new username.
=> Change all references of `janko-m` to `janko`

autoload/test/go/ginkgo.vim, spec/fixtures/ginkgo/normal_test.go, spec/ginkgo_spec.vim
This just makes nearest work with `When` and also fixes running by file and suite with it.
=> Fix ginkgo When and TestFile

doc/test.txt
=> Fix typo in docs/test.txt

README.md, autoload/test/python/pytest.vim
=> add poetry support to pytest

plugin/test.vim
This is very useful for selection of files actually.
=> TestFile: -complete=file

README.md, autoload/test/javascript/cypress.vim, doc/test.txt, plugin/test.vim, spec/cypress_spec.vim, spec/fixtures/cypress/integration_tests/context.spec.js, spec/fixtures/cypress/integration_tests/normal.spec.coffee, spec/fixtures/cypress/integration_tests/normal.spec.js, spec/fixtures/cypress/integration_tests/normal.spec.jsx, spec/fixtures/cypress/outside.spec.js, spec/fixtures/cypress/package.json
=> Add cypress javascript runner

Flavorfile, README.md, autoload/test/viml/testify.vim, plugin/test.vim, spec/fixtures/testify/test/normal.vim, spec/testify_spec.vim, spec/vspec_spec.vim
Hi,
I built a small unit testing plugin which works for me. Just wanted to add a runner for this so I followed suit based on the existing plugins for viml. I notice there is no documentation for the existing plugins in either the README or the doc/test.txt so I haven't added anything yet. I also do not see specs for any runners (I might not be looking in the right place, do point some out to me).
Let me know what you think or if any further changes are required.
=> Add runner for dhruvasagar/vim-testify

autoload/test/rust/cargotest.vim, spec/cargotest_spec.vim, spec/fixtures/cargo/src/lib.rs, spec/fixtures/cargo/src/nested/mod.rs, spec/fixtures/cargo/src/somemod.rs, spec/fixtures/cargo/src/too/nested.rs
Fix rust (cargo) test runner to find nearest unit tests and run file tests.
=> Resolve #389

autoload/test/ruby/minitest.vim
=> Fix Ruby Minitest command

autoload/test/python/djangotest.vim
=> Add recursive search for python module

README.md, autoload/test/strategy.vim, doc/test.txt
I apologize for introducing the breakage. Should I add a test for this? @codeinabox
=> Fix asyncrun_background global variable path

README.md, autoload/test/ruby/minitest.vim, spec/fixtures/minitest/test_classic.rb, spec/minitest_spec.vim
=> Support test filename prefix test_* for minitest

README.md
=> Update README to document correct pyunit runner (#453)

autoload/test/javascript/reactscripts.vim
This adds support for [react-app-rewired](https://github.com/timarney/react-app-rewired) in the ReactScripts runner
=> Check for and use react-app-rewired in ReactScripts runner

autoload/test/php/phpunit.vim
=> Use `php artisan test` if a Laravel project

autoload/test/javascript.vim
=> Update test#javascript#has_package to use json_decode if present

spec/phpunit_spec.vim, spec/reactscripts_spec.vim
This adds tests for the following merged pull requests #464, #468 and #471
=> Alternate executable tests

README.md
=> Update README to replace `janko/` references with `vim-test/`

autoload/test/javascript/tap.vim, spec/fixtures/tap/src/normal.test.js, spec/tap_spec.vim
=> Update TAP file pattern to handle files ending in .spec.js or .test.js

README.md
Given all the recent issues when working with a monorepo and #272 I feel it's best to add this limitation to the documentation and explain how users can mitigate this.
=> Make a note about working with a monorepo

.travis.yml
=> Fix rvm errors in Travis CI pipeline

autoload/test/javascript/tap.vim, spec/fixtures/tap/tests/subtest.js, spec/tap_spec.vim
This adds support for test nearest with TAP using `--grep=<pattern>`
=> Implement test nearest for TAP runner

autoload/test/php/phpunit.vim, spec/paratest_spec.vim
=> Only set --functional for nearest if the executable after overrides is paratest

README.md, autoload/test/strategy.vim, doc/test.txt
=> Add floaterm strategy

README.md
This adds some notes on PHPUnit alternate runners, something I meant to do after addressing #501
=> Add notes on PHPUnit alternate runners

README.md, autoload/test/java/maventest.vim, doc/test.txt, spec/maventest_spec.vim
=> Initial approach for integration tests in maven.

autoload/test/java/gradletest.vim, autoload/test/java/maventest.vim
- Just a minor script fix.
- Nothing to add to README.
- Nothing to add to document.
I noticed some syntax error in the source code (by [vimlparser](https://github.com/haya14busa/go-vimlparser)), so I fixed them.
=> Fix missing endif

autoload/test/javascript/denotest.vim, spec/denotest_spec.vim, spec/fixtures/deno/nearest_test.ts
The current `denotest` only seems to support `:TestFile`, so I added support for `:TestNearest`.
=> TestNearest support in "denotest"

autoload/test/base.vim, spec/fixtures/django/module/test_class.py, spec/pyunit_spec.vim
Ran into this issue myself and decided to have a stab at it. Closes #399.
Not a huge fan of the big conditional so happy to hear other approaches!
=> fix(base): detect nested namespace

autoload/test/javascript/jasmine.vim
This issues fixes some path problems when running vim-test on a windows instance of vim/nvim
=> Fixes issue #570 for running jasmine on windows

README.md, doc/test.txt
=> fix README typo

autoload/test/javascript/mocha.vim, spec/fixtures/mocha/test/normal.ts, spec/fixtures/mocha/test/normal.tsx, spec/mocha_spec.vim
=> Add .ts and .tsx support to mocha

autoload/test/go/delve.vim, spec/delve_spec.vim, spec/fixtures/delve/ginkgo_test.go
This successfully runs the tests nearest to my cursor, however I'm a very inexperienced vim programer and need to review a bit more.
~I'm still working on testing that breakpoints work correctly.~ verified
Closes #629 
=> Allow delve to work with Gingo

autoload/test/javascript/mocha.vim, spec/fixtures/mocha-typescript/package.json, spec/fixtures/mocha-typescript/src/addition.test.ts, spec/fixtures/mocha-typescript/test/normal.ts, spec/fixtures/mocha-typescript/test/normal.tsx, spec/mocha_typescript_spec.vim
=> Add typescript mocha

autoload/test/scala/blooptest.vim
=> Blooptest: remove trailing newline from project name

README.md, autoload/test/cpp/catch2.vim
=> Added support for changing binaries directory

autoload/test/javascript.vim, spec/fixtures/jest/__tests__/loop-test.js, spec/jest_spec.vim
=> Support jest inline loop test

README.md, autoload/test/rust/cargonextest.vim, doc/test.txt, plugin/test.vim, spec/cargonextest_spec.vim, spec/cargotest_spec.vim
=> Add cargo-nextest

autoload/test/go.vim, spec/fixtures/gotest/mypackage/normal_test.go, spec/fixtures/gotest/normal_test.go, spec/gotest_spec.vim
Test suites such as stretchr/testify uses methods as test functions
=> Added test suite method pattern

autoload/test/javascript/lab.vim, spec/fixtures/lab/package.json, spec/fixtures/lab/test/normal.ts, spec/lab_spec.vim
=> Add Typescript support to @hapijs/lab (#709)

autoload/test/javascript/vitest.vim, spec/vitest_spec.vim
=> feat: remove opinionated configuration for Vitest forcing no coverage

autoload/test/javascript/vuetestutils.vim, spec/vue_test_utils.vim
=> feat: remove opinionated configuration for Vue that turns off coverage

autoload/test/python.vim, autoload/test/python/pytest.vim, autoload/test/python/pyunit.vim, spec/pytest_spec.vim
=> feat: detect Python executable

autoload/test/strategy.vim
- [ x] Add fixtures and spec when implementing or updating a test runner
- [ x] Update the README accordingly
- [ x] Update the Vim documentation in `doc/test.txt`
=> fix/toggle-term-strategy: fixed wrong handling of single quotes

autoload/test/kotlin.vim, autoload/test/kotlin/gradletest.vim, spec/fixtures/gradle/kotlin/junit5/NestedTest.kt, spec/fixtures/gradle/kotlin/junit5/build.gradle, spec/kotlin_gradletest_spec.vim
=> Handle nested classes in kotlin tests

README.md, autoload/test/strategy.vim, doc/test.txt
=> Add neovim_sticky strategy, reusing already open terminal

doc/test.txt
=> docs: document g:test#runner_commands

.github/workflows/ci.yml
=> feat: add GitHub actions for running tests

autoload/test/python.vim, autoload/test/python/pytest.vim, autoload/test/python/pyunit.vim, spec/fixtures/pytest/test_expectation.py, spec/pytest_spec.vim
=> feat: pytest import detection

autoload/test/python.vim, spec/fixtures/pyunit/test_import_testcase.py, spec/pyunit_spec.vim
=> fix: update Python import detection to support from syntax

README.md, autoload/test/python/pytest.vim, doc/test.txt, spec/pytest_spec.vim
=> feat: pytest configuration detection

autoload/test/strategy.vim
Resolves #776 by disabling colour output for Dispatch strategy
=> fix: disable ANSI in Dispatch strategy with NO_COLOR=1

spec/denotest_spec.vim
=> test: add test for test#javascript#denotest#options

autoload/test/javascript/jest.vim, spec/fixtures/jest/__tests__/escaping-test.js, spec/jest_spec.vim
=> fix: escape () and [] in Jest nearest

README.md, autoload/test.vim, autoload/test/gleam/gleamtest.vim, autoload/test/strategy.vim, doc/test.txt, spec/gleam_spec.vim
=> Add support for gleam lang

autoload/test/erlang.vim, autoload/test/erlang/commontest.vim, spec/commontest_spec.vim, spec/fixtures/commontest/test_SUITE.erl
Also simplify test pattern customization for CommonTest runner.
=> Run test cases prefixed with t_ with CommonTest runner

autoload/test/go/ginkgo.vim, spec/fixtures/ginkgo/mypackage/version1_test.go, spec/fixtures/ginkgo/version1_test.go, spec/ginkgo_spec.vim
Resolve #645 by detecting if the test files imports Ginkgo version 1 or 2.
=> Ginkgo version 1 support

autoload/test/rust.vim, autoload/test/rust/cargonextest.vim, autoload/test/rust/cargotest.vim
=> Refactor shared Rust patterns

autoload/test/javascript.vim, autoload/test/javascript/playwright.vim
Improve Playwright detection so that it checks that the test file is a Playwright test.
=> Improve Playwright detection

autoload/test/javascript/jest.vim, spec/jest_spec.vim
=> feat: check for Jest config
